services:
  uptime-kuma:
    build:
      context: .
    image: uptime-kuma-litestream:local
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped
